import BOR from '../images/bor.png'
import MC from '../images/mc.png';
import EVER from '../images/ever.png'
import VAL from '../images/val.png'
import WOOL from '../images/wool.png'
import FCB from '../images/fcb.png'

export const GamesData = [
  {
    id: 1,
    time: 'Сегодня в 17:15',
    teamTitle1: 'Борусия',
    teamTitle2: 'Манчестер Сити',
    teamPhoto1: BOR,
    teamPhoto2: MC,
    count1: null,
    count2: null,
    forecast: true,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 2,
    time: 'Завтра в 09:20',
    teamTitle1: 'Евертрон',
    teamTitle2: 'Валенсия',
    teamPhoto1: EVER,
    teamPhoto2: VAL,
    count1: null,
    count2: null,
    forecast: false,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 3,
    time: 'Завтра в 09:20',
    teamTitle1: 'Борусия',
    teamTitle2: 'Манчестер Сити',
    teamPhoto1: BOR,
    teamPhoto2: MC,
    count1: null,
    count2: null,
    forecast: false,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 4,
    time: '20.12.2022, 19:45',
    teamTitle1: 'Вулвергемптон',
    teamTitle2: 'Евертрон',
    teamPhoto1: WOOL,
    teamPhoto2: EVER,
    count1: null,
    count2: null,
    forecast: false,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 5,
    time: '120',
    teamTitle1: 'Барселона',
    teamTitle2: 'Манчестер Сити',
    teamPhoto1: FCB,
    teamPhoto2: MC,
    count1: 2,
    count2: 3,
    forecast: true,
    live: true,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 6,
    time: '44',
    teamTitle1: 'Борусия',
    teamTitle2: 'Валенсия',
    teamPhoto1: BOR,
    teamPhoto2: VAL,
    count1: 0,
    count2: 1,
    forecast: false,
    live: true,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 7,
    time: '21.12.2022, 12:17',
    teamTitle1: 'Евертрон',
    teamTitle2: 'Валенсия',
    teamPhoto1: EVER,
    teamPhoto2: VAL,
    count1: 0,
    count2: 0,
    forecast: false,
    live: false,
    additionalCount1: 3,
    additionalCount2: 4,
  },
  {
    id: 8,
    time: '23.12.2022, 17:15',
    teamTitle1: 'Манчестер Сити',
    teamTitle2: 'Барселона',
    teamPhoto1: MC,
    teamPhoto2: FCB,
    count1: 2,
    count2: 4,
    forecast: true,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 9,
    time: '23.12.2022, 19:45',
    teamTitle1: 'Барселона',
    teamTitle2: 'Манчестер Сити',
    teamPhoto1: FCB,
    teamPhoto2: MC,
    count1: 0,
    count2: 2,
    forecast: false,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },
  {
    id: 10,
    time: '23.12.2022, 19:45',
    teamTitle1: 'Евертрон',
    teamTitle2: 'Валенсия',
    teamPhoto1: EVER,
    teamPhoto2: VAL,
    count1: 1,
    count2: 2,
    forecast: false,
    live: false,
    additionalCount1: null,
    additionalCount2: null,
  },

]